name: rfid_project
description: "Rfid project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type

  m_cubit:
    git:
      url: https://github.com/saedAlHanash/m_cubit

  cupertino_icons: ^1.0.8
  group_button: ^5.3.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  http: ^1.4.0
#  string_similarity:
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  carousel_slider: ^5.1.1
#  image_picker: ^1.1.2
#  url_launcher: ^6.3.1
  logger: ^2.5.0
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  collection: ^1.19.1
#  path_provider: ^2.1.5
#  path: ^1.9.1
#  flutter_local_notifications: ^19.2.1
  package_info_plus: ^8.3.0
#  share_plus: ^11.0.0
  awesome_dialog: ^3.2.1
  curved_navigation_bar: ^1.0.6
  pull_to_refresh: ^2.0.0
  go_router: ^15.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
    - family: semeBold
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf

flutter_intl:
  enabled: true
